### PR TITLE
Added test for reimport

### PR DESCRIPTION
**Pull request by starship9**
Added a basic test that checks for the .csv file extension in the reimport function

### CODE REVIEW

**Comment by tklebel** [comment]
Thanks for your effort! As you can see, the continuous-integration checks fail, so we are still not there.

For testing, we need to understand, what the function is supposed to do, and how we can make sure, that it is doing exactly that.

The test is concerned with this snippet:

```r
if (!identical(tools::file_ext(file), "csv")) {
  abort(paste("Only .csv-files which were generated by `jst_import` or",
              "`jst_import_zip` can be re-imported."))
}
```

This snippet checks the file extension of the supplied file. If it is a `.csv`, it does nothing. If it is something else, it will raise an error. With a test we want to check that it will raise an error, if we supply a wrong file.

The test could look like this:

```r
test_that("only .csv files can be re-imported", {
   expect_error(jst_re_import(jst_example("book.xml")), "Only .csv-files which")
 })
```

After you have implemented a test, you should run the tests locally to see, if everything works (there should be no errors when running the tests). When using RStudio, you can use the combination `cmd/ctrl + shift + t` to trigger the tests (alternatively just run `devtools::test()` in the console). If everything works, you can commit and push.

Please update your pull request, then we can either merge it or add more tests, however you like. 😀

**Comment by starship9** [comment]
I ran the tests using the `devtools::test()` function from the console, but all I got as output was a count of the tests that passed/failed, etc. Nothing more. Is there any way I can check which tests are failing?

**Comment by tklebel** [comment]
There are a few tests which I skip, which might hide the errors. 

The number tests that failed/passed/etc. is displayed on the end. Before this, you can see exactly which tests failed, passed or were skipped. In the following image I marked where you can see, that a test failed. Helpful is also the row, where the error occurred (in this case row 124).
error

**Comment by starship9** [comment]
On my screen all I get is the last section of the output, what am I doing wrong?

**Comment by tklebel** [comment]
I'm not sure. Maybe try to update/reinstall your packages/RStudio?

**Comment by starship9** [comment]
`test_that("only .csv files can be reimported", {
  expect_error(jst_re_import(jst_example("book.xml")),"Not a .csv file")
})`

This is what I've added to the `test-re-import.R` file.

**Comment by tklebel** [comment]
Which version of R are you running? The output shows, that you are only running two tests, after which execution stops. Are you able to run the examples (`devtools::run_examples()`)? It's hard to debug from here...

**Comment by starship9** [comment]
I was running 3.4 back then, updated to 3.5 now, the output from `devtools::test()` seems to be correct

**Comment by tklebel** [comment]
I think I found the source of the bug, which causes your problems. The CRAN version of `testthat` throws an error if there is a `library` call before the `context` call in a test file. Finding the bug was simple: googling the error message. Somehow I didn't think of that before. 🤷‍♂️ You should be able to resolve your problems by pulling the latest commit...

**Comment by starship9** [comment]
I added your changes, let me know if anything else is required!

**Comment by tklebel** [comment]
Thanks! If you feel like it, you're welcome to add more tests in a new PR :)

**Comment by starship9** [comment]
Awesome! Thanks so much, you've been great! :D

**Pull request merged**
